print('Hello World!')
print('Cual es tu nombre?')
miNombre = input()
print('Es un placer conocerte, ' + miNombre)
print('La longitud de tu nommbre es de: ')
print(len(miNombre))
print('Cual es tu edad?')
miEdad = input()
print('Tendras ' + str(int(miEdad) + 1) + ' en un anho') 